name: Sync Giscus Comments

on:
  discussion:
    types: [created, edited, deleted]
  discussion_comment:
    types: [created, edited, deleted]

jobs:
  trigger-sync:
    runs-on: ubuntu-latest
    steps:
      - name: Sync Giscus Database
        run: |
          curl -X POST \
            https://api.giscus.app/sync \
            -H "Authorization: Bearer ${{ secrets.GISCUS_TOKEN }}" \
            -H "Content-Type: application/json" 